"""add is_active to job_alerts

Revision ID: 04bdd0b6dfe1
Revises: d027e38b2bc7
Create Date: 2026-04-24 18:23:56.620925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bdd0b6dfe1'
down_revision = 'd027e38b2bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_alerts', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
