"""add is_fresher flag to jobs

Revision ID: 131be334d3ed
Revises: b2c8f4a7d9e1
Create Date: 2026-05-16 01:34:04.473120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131be334d3ed'
down_revision = 'b2c8f4a7d9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fresher', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_is_fresher'), ['is_fresher'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_is_fresher'))
        batch_op.drop_column('is_fresher')

    # ### end Alembic commands ###
