"""add reset token to users

Revision ID: 637300f19f9c
Revises: 6931da5a1324
Create Date: 2026-04-29 00:13:42.718713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637300f19f9c'
down_revision = '6931da5a1324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
