"""add news_cache table

Revision ID: 6931da5a1324
Revises: 04bdd0b6dfe1
Create Date: 2026-04-27 17:57:22.784073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6931da5a1324'
down_revision = '04bdd0b6dfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_cache')
    # ### end Alembic commands ###
