"""add resume builder tables

Revision ID: 6f641e78ba82
Revises: 637300f19f9c
Create Date: 2026-05-04 18:46:12.960659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f641e78ba82'
down_revision = '637300f19f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('best_for', sa.String(length=200), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('latex_code', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('resume_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latex_draft', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('jd_match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['resume_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_resumes', schema=None) as batch_op:
        batch_op.create_index('ix_user_resumes_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_user_resumes_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('model_used',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_chat_history_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('interview_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filler_words_detected', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('keywords_hit', sa.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('keywords_missing', sa.ARRAY(sa.String()), nullable=True))
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('question_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('question_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.create_index(batch_op.f('ix_interview_responses_session_id'), ['session_id'], unique=False)
        batch_op.drop_column('keyword_score')
        batch_op.drop_column('overall_score')

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_interview_sessions_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('questions_asked')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('feedback')
        batch_op.drop_column('structure_score')
        batch_op.drop_column('clarity_score')
        batch_op.drop_column('relevance_score')
        batch_op.drop_column('communication_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('communication_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('relevance_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clarity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('structure_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('questions_asked', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_interview_sessions_user_id'))
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('interview_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('keyword_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_interview_responses_session_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('question_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('question_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('keywords_missing')
        batch_op.drop_column('keywords_hit')
        batch_op.drop_column('score')
        batch_op.drop_column('filler_words_detected')
        batch_op.drop_column('word_count')
        batch_op.drop_column('duration_seconds')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_history_user_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('model_used',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user_resumes', schema=None) as batch_op:
        batch_op.drop_index('ix_user_resumes_user_id')
        batch_op.drop_index('ix_user_resumes_created_at')

    op.drop_table('user_resumes')
    op.drop_table('resume_templates')
    # ### end Alembic commands ###
