"""add resume_analyses table

Revision ID: d027e38b2bc7
Revises: 8475825be35b
Create Date: 2026-04-24 15:13:53.985420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd027e38b2bc7'
down_revision = '8475825be35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('ats_status', sa.String(length=50), nullable=True),
    sa.Column('skills_found', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('strengths', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('improvements', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('missing_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_analyses')
    # ### end Alembic commands ###
