"""fix template_id ondelete

Revision ID: fe7a4221a474
Revises: 1138b1b0f0fe
Create Date: 2026-05-07 13:07:09.544680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7a4221a474'
down_revision = '1138b1b0f0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_resumes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_resumes_template_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'resume_templates', ['template_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_resumes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_resumes_template_id_fkey'), 'resume_templates', ['template_id'], ['id'])

    # ### end Alembic commands ###
